server:
  port: 8082

spring:
  application:
    name: core-service

  datasource:
    url: jdbc:postgresql://localhost:5432/kizuna?currentSchema=core
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: core


  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8081/realms/seu-realm
      rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest
