server:
  port: 8083

spring:
  application:
    name: iam-service

  datasource:
    url: jdbc:postgresql://localhost:5432/kizuna?currentSchema=core
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: core


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/kizuna


