spring.application.name=kizuna-iam-service
server.servlet.context-path=/iam

keycloak.auth-server-url=http://localhost:8081
keycloak.realm=Kizuna
keycloak.client-id=kizuna-iam-service
keycloak.client-secret=7mVuzE8TZYGoKCOQYodIcBiBMsuB0a67

keycloak.grant-type=client_credentials

