server:
  port: 8086

spring:
  application:
    name:  notification-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/kizuna-notification

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/Kizuna


